// Code generated by swaggo/swag. DO NOT EDIT.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "API documentation for the Mafia game backend.",
        "title": "Mafia API",
        "contact": {},
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "paths": {},
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo instance with default values. Update these before serving docs.
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Mafia API",
	Description: "API documentation for the Mafia game backend.",
}

// ReadDoc returns the Swagger document for gin-swagger.
func (s *swaggerInfo) ReadDoc() string {
	doc := docTemplate
	doc = swag.Replace(doc, "{{.Title}}", s.Title)
	doc = swag.Replace(doc, "{{.Description}}", s.Description)
	doc = swag.Replace(doc, "{{.Version}}", s.Version)
	doc = swag.Replace(doc, "{{.Host}}", s.Host)
	doc = swag.Replace(doc, "{{.BasePath}}", s.BasePath)
	doc = swag.Replace(doc, "{{range .Schemes}}\"{{.}}\",{{end}}", swag.JoinByFormat(s.Schemes, "\"%v\"", ","))
	return doc
}

func init() {
	swag.Register(swag.Name, SwaggerInfo)
}
